#! /bin/sh

# MONITORS
xrandr --output DP-1 --primary --auto --output HDMI-0 --auto --right-of DP-1

# WORKSPACES
for monitor in $(xrandr -q | grep -w "connected" | cut -d " " -f1); do
	bspc monitor "$monitor" -d 1 2
done

# BSPWM CONFIG
bspc config window_gap          5
bspc config split_ratio		0.5
bspc config border_width	0
bspc config single_monocle	true
bspc config borderless_monocle	false
bspc config gapless_monocle	false
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	false
bspc config pointer_motion_interval	5
bspc config pointer_modifier		mod4
bspc config pointer_action1		move
bspc config pointer_action2		resize_side
bspc config pointer_action3		resize_corner

# BSPWM RULES
bspc rule -a pavucontrol state=floating center=true

# LANGUAGE SWITCH
setxkbmap -option grp:alt_shift_toggle us,ru

# FIX CURSOR
xsetroot -cursor_name left_ptr

# AUTOSTART
killall -w sxhkd picom feh polybar dunst
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
picom -b --config $HOME/.config/picom/picom.conf &
feh --bg-fill ~/Wallpapers/Wallpaper_0.png
polybar main -c $HOME/.config/polybar/config.ini &
polybar second -c $HOME/.config/polybar/config.ini &
dunst -config $HOME/.config/dunst/dunstrc &
